"""
verify_m_rank_test.py
======================
Reviewer's question on Chapter 5 Section 5.9 ("Timescale separation does not
predict it"): the section's headline is a controlled PARTIAL correlation of
log(M) with log(eps_plateau), residualised on a polynomial basis in
(log Te, log ne), reported negative in all twelve scope/basis combinations in
Table tab:partial_sweep (median -0.53). The reviewer calls that
over-engineered and asks a more direct question that removes the temperature
confound by construction rather than by regression: AT EACH FIXED Te, does
M(ne) correctly RANK eps_plateau(ne) across the density sweep? This is a
within-row Spearman correlation, no residualisation, no basis choice.

Nobody has run this before this script.

PREDICTION (written before computing anything below)
------------------------------------------------------
Chapter 5's regression-based claim is that larger M goes with LARGER error at
fixed (Te, ne) -- opposite sign to the naive stiffness argument. If that
finding is real and not an artifact of the polynomial control basis, the same
sign should show up in the much more elementary within-row rank test: for
most fixed-Te rows, M(ne) should rank eps_plateau(ne) in REVERSE, i.e.
rho_i < 0 for a majority of rows (median rho_i comfortably negative, and a
majority -- not just a plurality -- of rows with rho_i < 0).

The REFUTING observation would be: a majority of rows with rho_i > 0 (M and
eps_plateau co-ranked at fixed Te), which would mean the partial-correlation
sign is a feature of the chosen polynomial control basis and does not survive
the much weaker, assumption-free within-row test the reviewer is asking for.

Everything below is computed after this prediction was written; the prediction
is not adjusted after seeing the numbers.

WHAT THIS SCRIPT DOES
----------------------
Loads validation/divertor_map/divertor_map.csv (generated by
verify_divertor_map.py) and labels the i, j grid indices against
Te_grid_L.npy / ne_grid_L.npy via cr_context.py -- never redefining the grid.
Verifies the CSV's own Te, ne columns reproduce Te_grid[i], ne_grid[j] to
1e-9 relative before trusting the index labels.

For each direction (heat, cool) and pooled (both directions merged at a
common Te index i -- see caveat below), computes:

  1. Row-wise Spearman rho_i(M, eps_plateau) across ne, at each fixed Te row,
     over window_ok columns only (>=4 columns required). Distribution across
     rows, for three scopes: all Te, Te>=2 eV, and Te>=2 eV with ne>=1e14 cm^-3
     only (only 3 of 8 density columns qualify per direction -- reported, not
     silently worked around).
  2. Same, with lo_ELM_crash (the 100 us time-averaged bound) in place of
     eps_plateau, since that is what the census in Ch. 5 actually counts.
  3. Whether argmax_j M == argmax_j eps_plateau and argmin_j M == argmin_j
     eps_plateau at fixed Te, fraction of rows where each holds.
  4. The reverse question: at fixed ne (each of the 8 columns), Spearman
     rho_j(M, eps_plateau) across Te rows (Te>=2 eV only) -- to see whether
     the raw (uncontrolled) correlation reported in Ch. 5 (+0.76) is mostly
     the Te trend.
  5. The extremum comparison restricted to Te>=2 eV and window_ok (Chapter 5
     currently quotes extrema at [0,0] and [0,4], both below 2 eV).
  6. Plain Pearson and Spearman of log M vs log eps_plateau, pooled over
     window_ok rows with Te>=2 eV, for comparison against the row-wise
     numbers above and against Ch. 5's uncontrolled +0.76 / +0.416720
     (Te>=2 eV, linear-basis partial correlation numerator, from
     validation/partial_correlation/partial_correlation_sweep.csv).

CAVEAT ON "POOLED"
-------------------
"Pooled" here means: at a fixed base Te index i, the heat-direction and
cool-direction columns are merged into one set of (ne, M, eps) points before
computing rho_i. This roughly doubles the number of density columns behind
each row-wise statistic (up to 16 instead of 8), but it is NOT additional
density resolution -- it is the same 8 ne values sampled by two different
step directions. Scope (c) (ne>=1e14 only) can artificially clear the >=4
column threshold when pooled even though per-direction it cannot (only 3 of 8
ne columns qualify) -- flagged explicitly in the output rather than presented
as if it were 4+ genuinely distinct densities.

Report only. Writes to validation/m_rank_test/ only with --write. Modifies no
existing script or artifact.
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

sys.path.insert(0, str(Path(__file__).resolve().parent))
from cr_context import CRContext  # noqa: E402

MIN_COLS = 4  # minimum window_ok columns per Te row to compute a Spearman rho


def sha256(path: Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def read_header_lines(path: Path) -> list[str]:
    lines = []
    with open(path) as fh:
        for line in fh:
            if line.startswith("#"):
                lines.append(line.rstrip("\n"))
            else:
                break
    return lines


def build_direction_frames(df: pd.DataFrame) -> dict[str, pd.DataFrame]:
    heat = df[df.direction == "heat"].copy()
    cool = df[df.direction == "cool"].copy()
    pooled = df.copy()  # merges heat+cool at common i -- see docstring caveat
    return {"heat": heat, "cool": cool, "pooled": pooled}


def scope_mask(d: pd.DataFrame, scope: str) -> pd.DataFrame:
    if scope == "all":
        return d
    if scope == "Te>=2":
        return d[d.Te >= 2.0]
    if scope == "Te>=2_ne>=1e14":
        return d[(d.Te >= 2.0) & (d["ne"] >= 1e14)]
    raise ValueError(f"unknown scope {scope}")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--csv", default=None,
                     help="path to divertor_map.csv (default: pipeline location)")
    ap.add_argument("--write", action="store_true",
                     help="save outputs to validation/m_rank_test/")
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()

    ctx = CRContext.load()
    root = ctx.root
    csv_path = Path(args.csv).resolve() if args.csv else (
        root / "validation" / "divertor_map" / "divertor_map.csv")
    if not csv_path.is_file():
        raise FileNotFoundError(f"divertor map not found: {csv_path}")

    header_lines = read_header_lines(csv_path)
    df = pd.read_csv(csv_path, comment="#")

    required = {"direction", "i", "j", "Te", "ne", "tau_QSS", "tau_relax",
                "M", "window_ok", "eps_plateau", "lo_ELM_crash"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"{csv_path} missing required columns: {sorted(missing)}")

    # ---- label i, j against the pipeline's own grids; never redefine them ----
    Te_grid, ne_grid = ctx.te_grid, ctx.ne_grid
    i_idx, j_idx = df["i"].to_numpy(int), df["j"].to_numpy(int)
    if i_idx.max() >= len(Te_grid) or j_idx.max() >= len(ne_grid):
        raise ValueError(
            f"CSV i/j indices exceed grid sizes: max i={i_idx.max()} "
            f"(Te_grid has {len(Te_grid)}), max j={j_idx.max()} "
            f"(ne_grid has {len(ne_grid)}) -- stale grid or stale CSV")
    te_check = Te_grid[i_idx]
    ne_check = ne_grid[j_idx]
    if not np.allclose(te_check, df["Te"].to_numpy(), rtol=1e-9):
        bad = np.argmax(np.abs(te_check - df["Te"].to_numpy()))
        raise ValueError(
            f"Te column disagrees with Te_grid_L.npy indexed by column i "
            f"(worst row {bad}: CSV Te={df['Te'].iloc[bad]!r}, "
            f"Te_grid[i]={te_check[bad]!r}) -- grid is stale relative to the CSV")
    if not np.allclose(ne_check, df["ne"].to_numpy(), rtol=1e-9):
        bad = np.argmax(np.abs(ne_check - df["ne"].to_numpy()))
        raise ValueError(
            f"ne column disagrees with ne_grid_L.npy indexed by column j "
            f"(worst row {bad}: CSV ne={df['ne'].iloc[bad]!r}, "
            f"ne_grid[j]={ne_check[bad]!r}) -- grid is stale relative to the CSV")

    out_dir = args.out or (root / "validation" / "m_rank_test")

    lines: list[str] = []

    def say(s: str = "") -> None:
        print(s)
        lines.append(s)

    say("=" * 78)
    say("M-RANK TEST -- does M(ne) rank eps_plateau(ne) at fixed Te?")
    say(f"generated {datetime.now():%Y-%m-%d %H:%M}  by {Path(__file__).name}")
    say(f"python interpreter: {sys.executable}")
    say(f"repo root: {root}")
    say(f"loaded    : {csv_path}  ({len(df)} rows)")
    for h in header_lines:
        say(f"  (source header) {h}")
    say(f"Te grid   : {len(Te_grid)} points from cr_context (Te_grid_L.npy), "
        f"{Te_grid.min():.4f}-{Te_grid.max():.4f} eV")
    say(f"ne grid   : {len(ne_grid)} points from cr_context (ne_grid_L.npy), "
        f"{ne_grid.min():.3e}-{ne_grid.max():.3e} cm^-3")
    say("CSV i/j columns verified against Te_grid[i], ne_grid[j] to 1e-9 relative: OK")
    say("")
    say("PREDICTION (from the docstring, written before computing):")
    say("  Ch.5's partial correlation is negative in all 12 scope/basis combos")
    say("  (median -0.53): larger M goes with larger eps_plateau at fixed (Te,ne).")
    say("  Prediction: within-row rho_i(M, eps_plateau) across ne at fixed Te")
    say("  should be NEGATIVE for a majority of rows.")
    say("  Refutation would be: a MAJORITY of rows with rho_i > 0.")
    say("=" * 78)

    frames = build_direction_frames(df)
    scopes = ["all", "Te>=2", "Te>=2_ne>=1e14"]
    quantities = ["eps_plateau", "lo_ELM_crash"]

    detail_rows = []   # -> m_rank_test.csv
    summary_rows = []  # -> m_rank_test_summary.csv (part 1/2)

    say("\n" + "=" * 78)
    say("PART 1/2 -- row-wise Spearman rho_i(M, quantity) across ne, fixed Te")
    say("=" * 78)

    for dname, dsub in frames.items():
        for sname in scopes:
            ssub = scope_mask(dsub, sname)
            for qty in quantities:
                rhos, ns, used_i = [], [], []
                n_rows_seen = 0
                for i, grp in ssub.groupby("i"):
                    n_rows_seen += 1
                    gwin = grp[grp.window_ok]
                    n_cols = len(gwin)
                    if n_cols < MIN_COLS:
                        continue
                    rho, p = stats.spearmanr(gwin["M"], gwin[qty])
                    rhos.append(rho)
                    ns.append(n_cols)
                    used_i.append(int(i))
                    detail_rows.append(dict(
                        direction=dname, scope=sname, quantity=qty, i=int(i),
                        Te=float(Te_grid[int(i)]), n_cols=n_cols, rho_i=rho,
                        p_value=p))
                rhos_arr = np.asarray(rhos, dtype=float)
                n_rows = len(rhos_arr)
                if n_rows == 0:
                    med = mn = mx = fneg = fpos5 = fneg5 = float("nan")
                else:
                    med, mn, mx = np.median(rhos_arr), rhos_arr.min(), rhos_arr.max()
                    fneg = float((rhos_arr < 0).mean())
                    fpos5 = float((rhos_arr > 0.5).mean())
                    fneg5 = float((rhos_arr < -0.5).mean())
                summary_rows.append(dict(
                    test="row_wise_rank", direction=dname, scope=sname,
                    quantity=qty, n_rows_seen=n_rows_seen, n_rows_qualified=n_rows,
                    median_rho=med, min_rho=mn, max_rho=mx,
                    frac_rho_lt_0=fneg, frac_rho_gt_0p5=fpos5, frac_rho_lt_m0p5=fneg5))
                say(f"\n[{dname:>6}] scope={sname:<16} quantity={qty}")
                say(f"  rows seen={n_rows_seen}  rows qualified (>={MIN_COLS} "
                    f"window_ok cols)={n_rows}")
                if n_rows == 0:
                    say("  -- no rows qualify; cannot compute a distribution")
                    if sname == "Te>=2_ne>=1e14":
                        say("  (expected: only 3 of 8 ne columns satisfy ne>=1e14 "
                            "per direction, below the 4-column minimum)")
                else:
                    say(f"  median rho_i={med:+.4f}  min={mn:+.4f}  max={mx:+.4f}")
                    say(f"  frac(rho_i<0)={fneg:.3f}  frac(rho_i>0.5)={fpos5:.3f}  "
                        f"frac(rho_i<-0.5)={fneg5:.3f}")
                    if sname == "Te>=2_ne>=1e14" and dname != "pooled":
                        say("  NOTE: expected 0 qualified rows per direction (only 3 "
                            "ne>=1e14 columns) -- got a nonzero count, investigate")
                    if sname == "Te>=2_ne>=1e14" and dname == "pooled":
                        say("  CAVEAT: 'pooled' merges heat+cool at the same Te index, "
                            "so this scope can clear >=4 columns using only 3 distinct "
                            "ne values counted twice (once per step direction) -- NOT "
                            "genuine extra density resolution; see script docstring")

    say("\n" + "=" * 78)
    say("Rows with rho_i > 0 (going the OTHER way from the prediction), "
        "scope=all, quantity=eps_plateau")
    say("=" * 78)
    for dname, dsub in frames.items():
        rows_this = [r for r in detail_rows
                     if r["direction"] == dname and r["scope"] == "all"
                     and r["quantity"] == "eps_plateau" and r["rho_i"] > 0]
        say(f"[{dname}] {len(rows_this)} row(s) with rho_i>0:")
        for r in sorted(rows_this, key=lambda r: -r["rho_i"]):
            say(f"    i={r['i']:<3d} Te={r['Te']:.4f} eV  rho_i={r['rho_i']:+.4f}  "
                f"n_cols={r['n_cols']}  p={r['p_value']:.3g}")

    # ---- Part 3: argmax/argmin agreement -----------------------------------
    say("\n" + "=" * 78)
    say("PART 3 -- argmax_j / argmin_j agreement between M and eps_plateau, fixed Te")
    say("=" * 78)
    extremum_summary = []
    for dname, dsub in frames.items():
        for sname in ("all", "Te>=2"):
            ssub = scope_mask(dsub, sname)
            n_rows_seen = 0
            n_qualified = 0
            n_argmax_match = 0
            n_argmin_match = 0
            for i, grp in ssub.groupby("i"):
                n_rows_seen += 1
                gwin = grp[grp.window_ok]
                if len(gwin) < MIN_COLS:
                    continue
                n_qualified += 1
                jmax_M = gwin.loc[gwin["M"].idxmax(), "j"]
                jmax_eps = gwin.loc[gwin["eps_plateau"].idxmax(), "j"]
                jmin_M = gwin.loc[gwin["M"].idxmin(), "j"]
                jmin_eps = gwin.loc[gwin["eps_plateau"].idxmin(), "j"]
                if jmax_M == jmax_eps:
                    n_argmax_match += 1
                if jmin_M == jmin_eps:
                    n_argmin_match += 1
            frac_argmax = n_argmax_match / n_qualified if n_qualified else float("nan")
            frac_argmin = n_argmin_match / n_qualified if n_qualified else float("nan")
            extremum_summary.append(dict(
                test="argmax_argmin_match", direction=dname, scope=sname,
                n_rows_seen=n_rows_seen, n_rows_qualified=n_qualified,
                frac_argmax_match=frac_argmax, frac_argmin_match=frac_argmin))
            say(f"[{dname:>6}] scope={sname:<8} rows qualified={n_qualified}/{n_rows_seen}  "
                f"argmax match frac={frac_argmax:.3f} ({n_argmax_match}/{n_qualified})  "
                f"argmin match frac={frac_argmin:.3f} ({n_argmin_match}/{n_qualified})"
                if n_qualified else
                f"[{dname:>6}] scope={sname:<8} 0 rows qualified")

    # ---- Part 4: reverse question, fixed ne, across Te (Te>=2) -------------
    say("\n" + "=" * 78)
    say("PART 4 -- reverse: Spearman rho_j(M, eps_plateau) across Te (Te>=2 eV), fixed ne")
    say("=" * 78)
    reverse_rows = []
    for dname, dsub in frames.items():
        say(f"\n[{dname}]")
        for j in range(len(ne_grid)):
            sub = dsub[(dsub.Te >= 2.0) & (dsub.j == j) & (dsub.window_ok)]
            n = len(sub)
            if n < MIN_COLS:
                say(f"  j={j} ne={ne_grid[j]:.3e}  n={n} < {MIN_COLS}, skipped")
                reverse_rows.append(dict(direction=dname, j=j, ne=float(ne_grid[j]),
                                          n_rows=n, rho_j=float("nan"), p_value=float("nan")))
                continue
            rho, p = stats.spearmanr(sub["M"], sub["eps_plateau"])
            reverse_rows.append(dict(direction=dname, j=j, ne=float(ne_grid[j]),
                                      n_rows=n, rho_j=rho, p_value=p))
            say(f"  j={j} ne={ne_grid[j]:.3e}  n={n}  rho_j={rho:+.4f}  p={p:.3g}")

    # ---- Part 5: extremum comparison, Te>=2 & window_ok ---------------------
    say("\n" + "=" * 78)
    say("PART 5 -- extremum comparison restricted to Te>=2 eV & window_ok")
    say("(Chapter 5 currently quotes [0,0] and [0,4], both Te<2 eV)")
    say("=" * 78)
    extrema_rows = []
    for dname, dsub in frames.items():
        ssub = dsub[(dsub.Te >= 2.0) & (dsub.window_ok)]
        if ssub.empty:
            say(f"[{dname}] no window_ok rows with Te>=2 eV")
            continue
        rM = ssub.loc[ssub["M"].idxmax()]
        rE = ssub.loc[ssub["eps_plateau"].idxmax()]
        ratio = rM["ne"] / rE["ne"]
        extrema_rows.append(dict(
            direction=dname,
            maxM_dir=rM["direction"], maxM_i=int(rM["i"]), maxM_j=int(rM["j"]),
            maxM_Te=rM["Te"], maxM_ne=rM["ne"], maxM_M=rM["M"], maxM_eps=rM["eps_plateau"],
            maxEps_dir=rE["direction"], maxEps_i=int(rE["i"]), maxEps_j=int(rE["j"]),
            maxEps_Te=rE["Te"], maxEps_ne=rE["ne"], maxEps_M=rE["M"], maxEps_eps=rE["eps_plateau"],
            ne_ratio_maxM_over_maxEps=ratio))
        say(f"[{dname}]")
        say(f"  largest M    : dir={rM['direction']} [{int(rM['i'])},{int(rM['j'])}] "
            f"Te={rM['Te']:.4f} eV  ne={rM['ne']:.4e} cm^-3  M={rM['M']:.4e}  "
            f"eps_plateau={rM['eps_plateau']:.4f}")
        say(f"  largest eps  : dir={rE['direction']} [{int(rE['i'])},{int(rE['j'])}] "
            f"Te={rE['Te']:.4f} eV  ne={rE['ne']:.4e} cm^-3  M={rE['M']:.4e}  "
            f"eps_plateau={rE['eps_plateau']:.4f}")
        say(f"  ne ratio (largest-M point / largest-eps point) = {ratio:.4g}")

    # ---- Part 6: pooled log-log correlations, Te>=2, window_ok --------------
    say("\n" + "=" * 78)
    say("PART 6 -- pooled log M vs log eps_plateau, Te>=2 eV, window_ok rows")
    say("(for comparison with Ch.5's uncontrolled +0.76 and the linear-basis")
    say(" partial +0.416720 at Te>=2 eV from partial_correlation_sweep.csv)")
    say("=" * 78)
    pooled_loglog = []
    for dname, dsub in frames.items():
        ssub = dsub[(dsub.Te >= 2.0) & (dsub.window_ok)]
        n = len(ssub)
        if n < 2:
            say(f"[{dname}] n={n}, cannot compute")
            continue
        lm = np.log(ssub["M"].to_numpy())
        le = np.log(ssub["eps_plateau"].to_numpy())
        pear_r, pear_p = stats.pearsonr(lm, le)
        spear_r, spear_p = stats.spearmanr(lm, le)
        pooled_loglog.append(dict(direction=dname, n_rows=n,
                                   pearson_r=pear_r, pearson_p=pear_p,
                                   spearman_r=spear_r, spearman_p=spear_p))
        say(f"[{dname}] n={n}  pearson(logM,logEps)={pear_r:+.4f} (p={pear_p:.3g})  "
            f"spearman={spear_r:+.4f} (p={spear_p:.3g})")

    # ---- verdict --------------------------------------------------------------
    say("\n" + "=" * 78)
    say("VERDICT ON THE PREDICTION")
    say("=" * 78)
    key_row = next(r for r in summary_rows
                    if r["direction"] == "pooled" and r["scope"] == "all"
                    and r["quantity"] == "eps_plateau")
    held = key_row["frac_rho_lt_0"] is not None and key_row["frac_rho_lt_0"] > 0.5
    say(f"pooled, scope=all, eps_plateau: frac(rho_i<0)={key_row['frac_rho_lt_0']:.3f}, "
        f"median rho_i={key_row['median_rho']:+.4f}")
    say("PREDICTION HELD (majority of rows rank M and eps_plateau in reverse)"
        if held else
        "PREDICTION REFUTED (majority of rows rank M and eps_plateau the SAME way)")

    # ---- write outputs --------------------------------------------------------
    if args.write:
        out_dir.mkdir(parents=True, exist_ok=True)
        header = [
            f"# generated {datetime.now():%Y-%m-%d %H:%M} by {Path(__file__).name}",
            f"# python interpreter: {sys.executable}",
        ] + [f"# source {h[1:].strip()}" for h in header_lines] + [
            f"# source csv: {csv_path.relative_to(root)}  sha256 {sha256(csv_path)}",
            f"# min_cols_per_row {MIN_COLS}",
        ]

        detail_path = out_dir / "m_rank_test.csv"
        det_df = pd.DataFrame(detail_rows)
        with open(detail_path, "w") as fh:
            fh.write("\n".join(header) + "\n")
        det_df.to_csv(detail_path, mode="a", index=False)

        summary_path = out_dir / "m_rank_test_summary.csv"
        # combine the heterogeneous summary tables into one long-format file
        all_summary = []
        for r in summary_rows:
            all_summary.append(r)
        for r in extremum_summary:
            all_summary.append(r)
        for r in reverse_rows:
            r2 = dict(r)
            r2["test"] = "reverse_fixed_ne"
            all_summary.append(r2)
        for r in extrema_rows:
            r2 = dict(r)
            r2["test"] = "extrema_Te>=2_window_ok"
            all_summary.append(r2)
        for r in pooled_loglog:
            r2 = dict(r)
            r2["test"] = "pooled_loglog_Te>=2_window_ok"
            all_summary.append(r2)
        sum_df = pd.DataFrame(all_summary)
        with open(summary_path, "w") as fh:
            fh.write("\n".join(header) + "\n")
        sum_df.to_csv(summary_path, mode="a", index=False)

        txt_path = out_dir / "m_rank_test.txt"
        with open(txt_path, "w") as fh:
            fh.write("\n".join(header) + "\n")
            fh.write("\n".join(lines) + "\n")

        print(f"\nwrote {detail_path}")
        print(f"wrote {summary_path}")
        print(f"wrote {txt_path}")
    else:
        print("\n(--write not given; nothing saved)")


if __name__ == "__main__":
    main()
